builder:
  track: dev

labels:
  app: estafette-extension-git-clone
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

stages:
  git-clone:
    image: extensions/git-clone:stable
    when:
      status == 'succeeded' &&
      server == 'estafette'

  build:
    image: golang:1.10.2-alpine3.7
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test `go list ./... | grep -v /vendor/`
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: extensions/docker:dev
    action: build
    container: git-clone
    repositories:
    - extensions
    path: ./publish
    copy:
    - Dockerfile

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: git-clone
    repositories:
    - extensions
    tags:
    - dev

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(eoN9GnRnfeMLL7L0.ThpJZ1iBKSjR93u1IkQu8nm8dgdOrDeZsGkFMB-GPaAfPXUw4zH3kYjHu3rpW2hbZmuVMAviOrqQ-dNmujWOBHWQDMDPvwO2KO884caanb-LGx1CPAFF7qaPZpeU)
    name: ${ESTAFETTE_LABEL_APP}
    channels:
    - '#build-status'
    when:
      status == 'failed'

releases:
  beta:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: git-clone
        repositories:
        - extensions
        tags:
        - beta

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: git-clone
        repositories:
        - extensions
        tags:
        - stable
        - latest