builder:
  track: dev

labels:
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1

stages:
  git-clone:
    image: extensions/git-clone:stable
    when:
      status == 'succeeded' &&
      server == 'estafette'

  build:
    image: golang:1.13.0-alpine3.10
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    container: git-clone
    inline: |
      FROM alpine:3.9

      LABEL maintainer="estafette.io" \
            description="The ${ESTAFETTE_GIT_NAME} component is an Estafette extension to clone a git repository for builds handled by Estafette CI"

      RUN apk add --update --no-cache \
          git \
          && rm -rf /var/cache/apk/*

      COPY ${ESTAFETTE_GIT_NAME} /

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - extensions
    path: ./publish

  integration-test-override-max:
    image: extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
    repo: estafette.io
    branch: master
    subdir: test  

  integration-test-override-min:
    image: extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
    repo: estafette.io

  clean-working-directory:
    image: golang:1.13.0-alpine3.10
    commands:
    - rm -rf ..?* .[!.]* *

  integration-test-override-any-public:
    image: extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
    repo: https://github.com/golang/go.git
    branch: master
    subdir: .

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: git-clone
    repositories:
    - extensions

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: git-clone
        repositories:
        - extensions
        tags:
        - dev

  beta:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: git-clone
        repositories:
        - extensions
        tags:
        - beta

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: git-clone
        repositories:
        - extensions
        tags:
        - stable
        - latest

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'