builder:
  track: stable

labels:
  app: estafette-extension-git-clone
  team: estafette-team
  language: golang

pipelines:
  set-pending-build-status:
    image: extensions/github-status:dev
    status: pending
    when:
      server == 'estafette'

  build:
    image: golang:1.8.3-alpine3.6
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test `go list ./... | grep -v /vendor/`
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: docker:17.06.0-ce
    commands:
    - cp Dockerfile ./publish
    - docker build -t extensions/git-clone:${ESTAFETTE_BUILD_VERSION} ./publish

  push-to-docker-hub:
    image: docker:17.06.0-ce
    commands:
    - docker login --username=${ESTAFETTE_DOCKER_HUB_USERNAME} --password="${ESTAFETTE_DOCKER_HUB_PASSWORD}"
    - docker push extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
    - docker tag extensions/git-clone:${ESTAFETTE_BUILD_VERSION} extensions/git-clone:dev
    - docker push extensions/git-clone:dev
    when:
      status == 'succeeded' &&
      branch == 'master' &&
      server == 'gocd'

  set-build-status:
    image: extensions/github-status:dev
    when:
      server == 'estafette'

  slack-notify:
    image: golang:1.8.3-alpine3.6
    commands:
    - apk --update add curl
    - 'curl -X POST --data-urlencode ''payload={"channel": "#build-status", "username": "estafette-extension-git-clone", "text": "Build ''${ESTAFETTE_BUILD_VERSION}'' for ''${ESTAFETTE_LABEL_APP}'' has failed!"}'' ${ESTAFETTE_SLACK_WEBHOOK}'
    when:
      status == 'failed'