builder:
  track: stable

labels:
  app: estafette-extension-git-clone
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 0
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

pipelines:
  set-pending-build-status:
    image: extensions/github-status:dev
    status: pending
    when:
      server == 'estafette'

  build:
    image: golang:1.9.0-alpine3.6
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test `go list ./... | grep -v /vendor/`
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: docker:17.06.1-ce
    commands:
    - cp Dockerfile ./publish
    - docker build -t extensions/git-clone:${ESTAFETTE_BUILD_VERSION} ./publish

  push-to-docker-hub:
    image: docker:17.06.1-ce
    env:
      DOCKER_HUB_USERNAME: estafette.secret(793-0QLfe5QN3n1k.mDk5fL-_urybZ3T9Z3famkSZR68d-SrfqA==)
      DOCKER_HUB_PASSWORD: estafette.secret(3p0Geq5U12j98HXV.Eaupah0YHK6nQkMgT4WYzC5R8FRQbDk5H6aTo1saw35de2KQ)
    commands:
    - docker login --username=${DOCKER_HUB_USERNAME} --password="${DOCKER_HUB_PASSWORD}"
    - docker push extensions/git-clone:${ESTAFETTE_BUILD_VERSION}
    - docker tag extensions/git-clone:${ESTAFETTE_BUILD_VERSION} extensions/git-clone:dev
    - docker push extensions/git-clone:dev
    when:
      status == 'succeeded' &&
      branch == 'master' &&
      server == 'gocd'

  set-build-status:
    image: extensions/github-status:dev
    when:
      server == 'estafette'

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(eoN9GnRnfeMLL7L0.ThpJZ1iBKSjR93u1IkQu8nm8dgdOrDeZsGkFMB-GPaAfPXUw4zH3kYjHu3rpW2hbZmuVMAviOrqQ-dNmujWOBHWQDMDPvwO2KO884caanb-LGx1CPAFF7qaPZpeU)
    name: ${ESTAFETTE_LABEL_APP}
    channels:
    - '#build-status'
    when:
      status == 'failed'